<?php
/**
 * AvailableCurrencyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * currencyapi
 *
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AvailableCurrencyTest Class Doc Comment
 *
 * @category    Class */
// * @description Details of a specific currency
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AvailableCurrencyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AvailableCurrency"
     */
    public function testAvailableCurrency()
    {
    }

    /**
     * Test attribute "iso_currency_code"
     */
    public function testPropertyIsoCurrencyCode()
    {
    }

    /**
     * Test attribute "currency_symbol"
     */
    public function testPropertyCurrencySymbol()
    {
    }

    /**
     * Test attribute "currency_english_name"
     */
    public function testPropertyCurrencyEnglishName()
    {
    }

    /**
     * Test attribute "country_name"
     */
    public function testPropertyCountryName()
    {
    }

    /**
     * Test attribute "country_three_letter_code"
     */
    public function testPropertyCountryThreeLetterCode()
    {
    }

    /**
     * Test attribute "country_iso_two_letter_code"
     */
    public function testPropertyCountryIsoTwoLetterCode()
    {
    }

    /**
     * Test attribute "is_european_union_member"
     */
    public function testPropertyIsEuropeanUnionMember()
    {
    }
}
