<?php
/**
 * ConvertedCurrencyResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * currencyapi
 *
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConvertedCurrencyResultTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of performing a Convert Currency operation
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConvertedCurrencyResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConvertedCurrencyResult"
     */
    public function testConvertedCurrencyResult()
    {
    }

    /**
     * Test attribute "converted_price"
     */
    public function testPropertyConvertedPrice()
    {
    }

    /**
     * Test attribute "iso_currency_code"
     */
    public function testPropertyIsoCurrencyCode()
    {
    }

    /**
     * Test attribute "currency_symbol"
     */
    public function testPropertyCurrencySymbol()
    {
    }

    /**
     * Test attribute "formatted_price_as_string"
     */
    public function testPropertyFormattedPriceAsString()
    {
    }
}
