<?php
/**
 * CurrencyExchangeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * currencyapi
 *
 * The currency APIs help you retrieve exchange rates and convert prices between currencies easily.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CurrencyExchangeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CurrencyExchangeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for currencyExchangeConvertCurrency
     *
     * Converts a price from the source currency into the destination currency.
     *
     */
    public function testCurrencyExchangeConvertCurrency()
    {
    }

    /**
     * Test case for currencyExchangeGetAvailableCurrencies
     *
     * Get a list of available currencies and corresponding countries.
     *
     */
    public function testCurrencyExchangeGetAvailableCurrencies()
    {
    }

    /**
     * Test case for currencyExchangeGetExchangeRate
     *
     * Gets the exchange rate from the source currency into the destination currency.
     *
     */
    public function testCurrencyExchangeGetExchangeRate()
    {
    }
}
